SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[OW_CUSTOMERS] (
	[CUST_ID] decimal(38, 0) NOT NULL,
	[NAME] varchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ADDRESS] varchar(64) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[BALANCE] decimal(38, 0) DEFAULT ((0)),
	[CREDIT_LMT] decimal(38, 0) DEFAULT ((0)),
	CONSTRAINT [OW_CUSTOMERS_PK] PRIMARY KEY([CUST_ID]) WITH (FILLFACTOR=100) ON [PRIMARY]
) ON [PRIMARY]